# Common defines for Makefile build system
#

override makefile_defs_included:=1

PREFIX ?= /usr/local
BASENAME ?= secsipid
TOOLNAME ?= secsipidx

LIBVERMAJ ?= 1
LIBVERMIN ?= 3
LIBVERLEV ?= 2
LIBVERSION ?= ${LIBVERMAJ}.${LIBVERMIN}.${LIBVERLEV}

GO111MODVAL ?= on

GO ?= go

OS := $(shell uname -s | sed -e s/SunOS/solaris/ -e s/CYGWIN.*/cygwin/ \
		 | tr "[A-Z]" "[a-z]" | tr "/" "_")

